### ISSUE TITLE
Add double quotes around war parameter in GWT run config

### ISSUE THREAD

**Issue by evpaassen** [eveoh/intellij-mytimetable#36]
It doesn't support spaces atm.

`-war C:/space here/build/classes/artifacts/mytimetable-web-war/exploded/mytimetable-web-server.war`

**Comment by evpaassen** [comment]
@boriseveoh, waren er nou nog meer problemen met spaties in het init script?

**Comment by boriseveoh** [comment]
Ik heb mijn fixes gecommit in fb_add-quotes.

@evpaassen We liepen nog tegen iets anders met een GWT path aan, maar dat hadden we volgens mij op een andere manier gefixt (local path zonder spaties gebruiken volgens mij).
